<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obat = collect([
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 1,
            //     'nama_obat' => 'Paracetamol',
            //     'takaran_minum' => '3 tablet',
            //     'jml_kali_minum' => '3 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Setelah makan',
            //     'golongan_obat' => 'Analgesik',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi, Siang, Malam',
            //     'keterangan' => 'Obat untuk mengurangi nyeri',
            //     'kontraindikasi' => 'Hati yang bermasalah',
            //     'pola_makan' => 'Sesuaikan',
            //     'interaksi_obat' => 'Aspirin',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 500,
            //     'informasi_tambahan' => 'Tidak lebih dari 4 gram per hari',
            //     'efek_samping' => 'Mual',
            //     'indikasi' => 'Demam, Nyeri',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 2,
            //     'nama_obat' => 'Ciprofloxacin',
            //     'takaran_minum' => '2 tablet',
            //     'jml_kali_minum' => '2 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Sebelum makan',
            //     'golongan_obat' => 'Antibiotik',
            //     'jumlah_obat' => '20',
            //     'waktu_minum' => 'Pagi, Malam',
            //     'keterangan' => 'Obat untuk infeksi bakteri',
            //     'kontraindikasi' => 'Penyakit ginjal',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Aluminium',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 500,
            //     'informasi_tambahan' => 'Hindari paparan sinar matahari langsung',
            //     'efek_samping' => 'Mual, diare',
            //     'indikasi' => 'Infeksi saluran kemih',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 3,
            //     'nama_obat' => 'Furosemide',
            //     'takaran_minum' => '1 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Pagi hari',
            //     'golongan_obat' => 'Diuretik',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi',
            //     'keterangan' => 'Obat untuk tekanan darah tinggi',
            //     'kontraindikasi' => 'Gagal ginjal',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Aminoglikosida',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 40,
            //     'informasi_tambahan' => 'Periksa kadar elektrolit secara rutin',
            //     'efek_samping' => 'Dehidrasi',
            //     'indikasi' => 'Edema',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 4,
            //     'nama_obat' => 'Amoxicillin',
            //     'takaran_minum' => '2 tablet',
            //     'jml_kali_minum' => '2 kali',
            //     'bentuk_obat' => 'Kapsul',
            //     'aturan_pakai' => 'Sebelum makan',
            //     'golongan_obat' => 'Antibiotik',
            //     'jumlah_obat' => '20',
            //     'waktu_minum' => 'Pagi, Malam',
            //     'keterangan' => 'Obat untuk infeksi',
            //     'kontraindikasi' => 'Alergi penisilin',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Metotreksat',
            //     'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
            //     'kekuatan_sediaan' => 250,
            //     'informasi_tambahan' => 'Minum habis sesuai resep',
            //     'efek_samping' => 'Diare',
            //     'indikasi' => 'Infeksi bakteri',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 5,
            //     'nama_obat' => 'Cetirizine',
            //     'takaran_minum' => '3 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Sebelum tidur',
            //     'golongan_obat' => 'Antihistamin',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Malam',
            //     'keterangan' => 'Obat untuk alergi',
            //     'kontraindikasi' => 'Penyakit hati',
            //     'pola_makan' => 'Tidak ada',
            //     'interaksi_obat' => 'Alkohol',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat sejuk',
            //     'kekuatan_sediaan' => 10,
            //     'informasi_tambahan' => 'Hindari alkohol saat minum',
            //     'efek_samping' => 'Mengantuk',
            //     'indikasi' => 'Alergi musiman',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 6,
            //     'nama_obat' => 'Ibuprofen',
            //     'takaran_minum' => '2 tablet',
            //     'jml_kali_minum' => '3 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Setelah makan',
            //     'golongan_obat' => 'NSAID',
            //     'jumlah_obat' => '20',
            //     'waktu_minum' => 'Pagi, Siang, Malam',
            //     'keterangan' => 'Obat untuk nyeri',
            //     'kontraindikasi' => 'Asma',
            //     'pola_makan' => 'Setelah makan',
            //     'interaksi_obat' => 'Antikoagulan',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 400,
            //     'informasi_tambahan' => 'Minum cukup air',
            //     'efek_samping' => 'Sakit perut',
            //     'indikasi' => 'Nyeri',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 7,
            //     'nama_obat' => 'Metformin',
            //     'takaran_minum' => '3 tablet',
            //     'jml_kali_minum' => '2 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Sebelum makan',
            //     'golongan_obat' => 'Antidiabetik',
            //     'jumlah_obat' => '60',
            //     'waktu_minum' => 'Pagi, Malam',
            //     'keterangan' => 'Obat untuk diabetes',
            //     'kontraindikasi' => 'Gagal ginjal',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Insulin',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 500,
            //     'informasi_tambahan' => 'Hindari alkohol',
            //     'efek_samping' => 'Mulas',
            //     'indikasi' => 'Diabetes tipe 2',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 8,
            //     'nama_obat' => 'Lisinopril',
            //     'takaran_minum' => '2 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Pagi hari',
            //     'golongan_obat' => 'Antihipertensi',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi',
            //     'keterangan' => 'Obat untuk hipertensi',
            //     'kontraindikasi' => 'Hamil',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Diuretik',
            //     'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
            //     'kekuatan_sediaan' => 10,
            //     'informasi_tambahan' => 'Periksa tekanan darah secara rutin',
            //     'efek_samping' => 'Pusing',
            //     'indikasi' => 'Hipertensi',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 8,
            //     'nama_obat' => 'Simvastatin',
            //     'takaran_minum' => '3 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Malam hari',
            //     'golongan_obat' => 'Hipolipidemik',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Malam',
            //     'keterangan' => 'Obat untuk kolesterol',
            //     'kontraindikasi' => 'Penyakit hati',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Antibiotik',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 20,
            //     'informasi_tambahan' => 'Periksa kadar kolesterol secara rutin',
            //     'efek_samping' => 'Nyeri otot',
            //     'indikasi' => 'Hiperlipidemia',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 9,
            //     'nama_obat' => 'Amlodipine',
            //     'takaran_minum' => '1 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Pagi hari',
            //     'golongan_obat' => 'Antihipertensi',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi',
            //     'keterangan' => 'Obat untuk tekanan darah tinggi',
            //     'kontraindikasi' => 'Hamil',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Diuretik',
            //     'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
            //     'kekuatan_sediaan' => 5,
            //     'informasi_tambahan' => 'Periksa tekanan darah secara rutin',
            //     'efek_samping' => 'Pusing',
            //     'indikasi' => 'Hipertensi',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 10,
            //     'nama_obat' => 'Omeprazole',
            //     'takaran_minum' => '2 tablet',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Kapsul',
            //     'aturan_pakai' => 'Sebelum makan',
            //     'golongan_obat' => 'Antasida',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi',
            //     'keterangan' => 'Obat untuk sakit maag',
            //     'kontraindikasi' => 'Alergi',
            //     'pola_makan' => 'Tidak ada',
            //     'interaksi_obat' => 'Warfarin',
            //     'petunjuk_penyimpanan' => 'Simpan di tempat kering',
            //     'kekuatan_sediaan' => 20,
            //     'informasi_tambahan' => 'Minum dengan air',
            //     'efek_samping' => 'Sakit kepala',
            //     'indikasi' => 'Maag',
            // ],
            // [
            //     'id_apoteker' => 1,
            //     'id_pasien' => 10,
            //     'nama_obat' => 'Levothyroxine',
            //     'takaran_minum' => '50 mcg',
            //     'jml_kali_minum' => '1 kali',
            //     'bentuk_obat' => 'Tablet',
            //     'aturan_pakai' => 'Pagi hari',
            //     'golongan_obat' => 'Hormon',
            //     'jumlah_obat' => '30',
            //     'waktu_minum' => 'Pagi',
            //     'keterangan' => 'Obat untuk hipotiroidisme',
            //     'kontraindikasi' => 'Alergi',
            //     'pola_makan' => 'Sesuai anjuran dokter',
            //     'interaksi_obat' => 'Antikoagulan',
            //     'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
            //     'kekuatan_sediaan' => 50,
            //     'informasi_tambahan' => 'Periksa kadar hormon tiroid secara rutin',
            //     'efek_samping' => 'Jantung berdebar',
            //     'indikasi' => 'Hipotiroidisme',
            // ],

             [
                'id_apoteker' => 1,
                'id_pasien' => 1,
                'nama_obat' => 'Paracetamol',
                'takaran_minum' => '500 mg',
                'jml_kali_minum' => 3,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'tablet',
                'kemasan_obat' => 'strip',
                'aturan_pakai' => 'Sesudah makan',
                'golongan_obat' => 'Analgesik',
                'jumlah_obat' => '10 tablet',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Obat penurun demam dan nyeri',
                'harga_satuan' => 1000,
                'kontraindikasi' => 'Alergi paracetamol',
                'pola_makan' => 'Biasa',
                'interaksi_obat' => 'Dengan alkohol',
                'petunjuk_penyimpanan' => 'Suhu ruang, hindari sinar matahari',
                'kekuatan_sediaan' => 500,
                'informasi_tambahan' => 'Tersedia generik',
                'efek_samping' => 'Mual, ruam kulit',
                'indikasi' => 'Demam, nyeri ringan',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 2,
                'nama_obat' => 'Amoxicillin',
                'takaran_minum' => '250 mg',
                'jml_kali_minum' => 3,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'kapsul',
                'kemasan_obat' => 'botol plastik',
                'aturan_pakai' => 'Sebelum makan',
                'golongan_obat' => 'Antibiotik',
                'jumlah_obat' => '15 kapsul',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Antibiotik spektrum luas',
                'harga_satuan' => 1500,
                'kontraindikasi' => 'Alergi penisilin',
                'pola_makan' => 'Biasa',
                'interaksi_obat' => 'Dengan kontrasepsi oral',
                'petunjuk_penyimpanan' => 'Tempat sejuk dan kering',
                'kekuatan_sediaan' => 250,
                'informasi_tambahan' => 'Resep dokter',
                'efek_samping' => 'Diare, mual',
                'indikasi' => 'Infeksi bakteri',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 3,
                'nama_obat' => 'Dexamethasone',
                'takaran_minum' => '0.5 mg',
                'jml_kali_minum' => 1,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'puyer',
                'kemasan_obat' => 'sachet',
                'aturan_pakai' => 'Sesudah makan',
                'golongan_obat' => 'Kortikosteroid',
                'jumlah_obat' => '10 sachet',
                'waktu_minum' => 'Malam',
                'keterangan' => 'Anti-inflamasi',
                'harga_satuan' => 1200,
                'kontraindikasi' => 'Infeksi jamur sistemik',
                'pola_makan' => 'Biasa',
                'interaksi_obat' => 'Aspirin, insulin',
                'petunjuk_penyimpanan' => 'Tempat kering',
                'kekuatan_sediaan' => 0.5,
                'informasi_tambahan' => 'Jangan digunakan jangka panjang',
                'efek_samping' => 'Retensi cairan',
                'indikasi' => 'Radang, alergi',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 4,
                'nama_obat' => 'Ambroxol',
                'takaran_minum' => '5 ml',
                'jml_kali_minum' => 2,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'sirup',
                'kemasan_obat' => 'botol kaca',
                'aturan_pakai' => 'Setelah makan',
                'golongan_obat' => 'Mukolitik',
                'jumlah_obat' => '1 botol',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Mengencerkan dahak',
                'harga_satuan' => 18000,
                'kontraindikasi' => 'Ulkus peptikum aktif',
                'pola_makan' => 'Biasa',
                'interaksi_obat' => 'Antibiotik tertentu',
                'petunjuk_penyimpanan' => 'Suhu ruang',
                'kekuatan_sediaan' => 30,
                'informasi_tambahan' => 'Kocok sebelum pakai',
                'efek_samping' => 'Mual, diare',
                'indikasi' => 'Batuk berdahak',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 5,
                'nama_obat' => 'Tetes Mata Insto',
                'takaran_minum' => '2 tetes',
                'jml_kali_minum' => 3,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'tetes',
                'kemasan_obat' => 'botol kecil',
                'aturan_pakai' => 'Teteskan ke mata',
                'golongan_obat' => 'Oftalmik',
                'jumlah_obat' => '1 botol',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Mengatasi iritasi mata',
                'harga_satuan' => 7000,
                'kontraindikasi' => 'Infeksi mata berat',
                'pola_makan' => 'Tidak relevan',
                'interaksi_obat' => 'Tidak diketahui',
                'petunjuk_penyimpanan' => 'Suhu ruang, tutup rapat',
                'kekuatan_sediaan' => 10,
                'informasi_tambahan' => 'Hanya untuk mata',
                'efek_samping' => 'Perih sesaat',
                'indikasi' => 'Mata merah',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 5 data tambahan:
            [
                'id_apoteker' => 1,
                'id_pasien' => 6,
                'nama_obat' => 'Hydrocortisone',
                'takaran_minum' => 'Oles tipis',
                'jml_kali_minum' => 2,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'krim',
                'kemasan_obat' => 'tube',
                'aturan_pakai' => 'Oleskan pada kulit',
                'golongan_obat' => 'Kortikosteroid',
                'jumlah_obat' => '1 tube',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Mengurangi gatal/radang',
                'harga_satuan' => 9000,
                'kontraindikasi' => 'Infeksi jamur',
                'pola_makan' => 'Tidak relevan',
                'interaksi_obat' => 'Tidak signifikan',
                'petunjuk_penyimpanan' => 'Suhu ruang',
                'kekuatan_sediaan' => 10,
                'informasi_tambahan' => 'Jangan kena mata',
                'efek_samping' => 'Iritasi lokal',
                'indikasi' => 'Eksim, ruam kulit',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 7,
                'nama_obat' => 'Gentamicin',
                'takaran_minum' => 'Oles tipis',
                'jml_kali_minum' => 3,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'salep',
                'kemasan_obat' => 'tube',
                'aturan_pakai' => 'Oleskan pada luka',
                'golongan_obat' => 'Antibiotik topikal',
                'jumlah_obat' => '1 tube',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Mengobati infeksi kulit',
                'harga_satuan' => 8500,
                'kontraindikasi' => 'Luka terbuka luas',
                'pola_makan' => 'Tidak relevan',
                'interaksi_obat' => 'Tidak diketahui',
                'petunjuk_penyimpanan' => 'Tutup rapat setelah pakai',
                'kekuatan_sediaan' => 5,
                'informasi_tambahan' => 'Obat luar',
                'efek_samping' => 'Reaksi lokal',
                'indikasi' => 'Infeksi kulit ringan',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 8,
                'nama_obat' => 'Voltaren',
                'takaran_minum' => 'Oles secukupnya',
                'jml_kali_minum' => 3,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'gel',
                'kemasan_obat' => 'tube',
                'aturan_pakai' => 'Oles pada area nyeri',
                'golongan_obat' => 'NSAID topikal',
                'jumlah_obat' => '1 tube',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Anti nyeri otot',
                'harga_satuan' => 12000,
                'kontraindikasi' => 'Kulit luka terbuka',
                'pola_makan' => 'Tidak relevan',
                'interaksi_obat' => 'Tidak signifikan',
                'petunjuk_penyimpanan' => 'Tempat kering',
                'kekuatan_sediaan' => 10,
                'informasi_tambahan' => 'Tidak untuk anak <12 th',
                'efek_samping' => 'Kemerahan lokal',
                'indikasi' => 'Nyeri otot',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 9,
                'nama_obat' => 'Metformin',
                'takaran_minum' => '500 mg',
                'jml_kali_minum' => 2,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'tablet',
                'kemasan_obat' => 'strip',
                'aturan_pakai' => 'Sesudah makan',
                'golongan_obat' => 'Antidiabetik oral',
                'jumlah_obat' => '20 tablet',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Menurunkan gula darah',
                'harga_satuan' => 1400,
                'kontraindikasi' => 'Gagal ginjal',
                'pola_makan' => 'Rendah gula',
                'interaksi_obat' => 'Insulin',
                'petunjuk_penyimpanan' => 'Suhu ruang',
                'kekuatan_sediaan' => 500,
                'informasi_tambahan' => 'Cek gula darah rutin',
                'efek_samping' => 'Diare, mual',
                'indikasi' => 'Diabetes Tipe 2',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 10,
                'nama_obat' => 'Ranitidine',
                'takaran_minum' => '150 mg',
                'jml_kali_minum' => 2,
                'jml_obat_per_minum' => 1,
                'bentuk_obat' => 'tablet',
                'kemasan_obat' => 'strip',
                'aturan_pakai' => 'Sebelum tidur',
                'golongan_obat' => 'Antasida',
                'jumlah_obat' => '10 tablet',
                'waktu_minum' => 'Malam',
                'keterangan' => 'Menurunkan asam lambung',
                'harga_satuan' => 1300,
                'kontraindikasi' => 'Porfiria akut',
                'pola_makan' => 'Hindari makanan pedas',
                'interaksi_obat' => 'Warfarin',
                'petunjuk_penyimpanan' => 'Suhu ruang',
                'kekuatan_sediaan' => 150,
                'informasi_tambahan' => 'Jangan dikunyah',
                'efek_samping' => 'Sakit kepala',
                'indikasi' => 'Maag',
                'status_ketersediaan_obat' => 'Stocked',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $obat->each(fn($put) => DB::table('obat')->insert($put));
    }
}
