<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ObatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $obat = collect([
            [
                'id_apoteker' => 1,
                'id_pasien' => 1,
                'nama_obat' => 'Paracetamol',
                'takaran_minum' => '500 mg',
                'jml_kali_minum' => '3 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Setelah makan',
                'golongan_obat' => 'Analgesik',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Obat untuk mengurangi nyeri',
                'kontraindikasi' => 'Hati yang bermasalah',
                'pola_makan' => 'Sesuaikan',
                'interaksi_obat' => 'Aspirin',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '500 mg',
                'informasi_tambahan' => 'Tidak lebih dari 4 gram per hari',
                'efek_samping' => 'Mual',
                'indikasi' => 'Demam, Nyeri',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 2,
                'nama_obat' => 'Ciprofloxacin',
                'takaran_minum' => '500 mg',
                'jml_kali_minum' => '2 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Sebelum makan',
                'golongan_obat' => 'Antibiotik',
                'jumlah_obat' => '20',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Obat untuk infeksi bakteri',
                'kontraindikasi' => 'Penyakit ginjal',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Aluminium',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '500 mg',
                'informasi_tambahan' => 'Hindari paparan sinar matahari langsung',
                'efek_samping' => 'Mual, diare',
                'indikasi' => 'Infeksi saluran kemih',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 3,
                'nama_obat' => 'Furosemide',
                'takaran_minum' => '40 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Pagi hari',
                'golongan_obat' => 'Diuretik',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi',
                'keterangan' => 'Obat untuk tekanan darah tinggi',
                'kontraindikasi' => 'Gagal ginjal',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Aminoglikosida',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '40 mg',
                'informasi_tambahan' => 'Periksa kadar elektrolit secara rutin',
                'efek_samping' => 'Dehidrasi',
                'indikasi' => 'Edema',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 4,
                'nama_obat' => 'Amoxicillin',
                'takaran_minum' => '250 mg',
                'jml_kali_minum' => '2 kali',
                'bentuk_obat' => 'Kapsul',
                'aturan_pakai' => 'Sebelum makan',
                'golongan_obat' => 'Antibiotik',
                'jumlah_obat' => '20',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Obat untuk infeksi',
                'kontraindikasi' => 'Alergi penisilin',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Metotreksat',
                'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
                'kekuatan_sediaan' => '250 mg',
                'informasi_tambahan' => 'Minum habis sesuai resep',
                'efek_samping' => 'Diare',
                'indikasi' => 'Infeksi bakteri',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 5,
                'nama_obat' => 'Cetirizine',
                'takaran_minum' => '10 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Sebelum tidur',
                'golongan_obat' => 'Antihistamin',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Malam',
                'keterangan' => 'Obat untuk alergi',
                'kontraindikasi' => 'Penyakit hati',
                'pola_makan' => 'Tidak ada',
                'interaksi_obat' => 'Alkohol',
                'petunjuk_penyimpanan' => 'Simpan di tempat sejuk',
                'kekuatan_sediaan' => '10 mg',
                'informasi_tambahan' => 'Hindari alkohol saat minum',
                'efek_samping' => 'Mengantuk',
                'indikasi' => 'Alergi musiman',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 6,
                'nama_obat' => 'Ibuprofen',
                'takaran_minum' => '400 mg',
                'jml_kali_minum' => '3 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Setelah makan',
                'golongan_obat' => 'NSAID',
                'jumlah_obat' => '20',
                'waktu_minum' => 'Pagi, Siang, Malam',
                'keterangan' => 'Obat untuk nyeri',
                'kontraindikasi' => 'Asma',
                'pola_makan' => 'Setelah makan',
                'interaksi_obat' => 'Antikoagulan',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '400 mg',
                'informasi_tambahan' => 'Minum cukup air',
                'efek_samping' => 'Sakit perut',
                'indikasi' => 'Nyeri',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 7,
                'nama_obat' => 'Metformin',
                'takaran_minum' => '500 mg',
                'jml_kali_minum' => '2 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Sebelum makan',
                'golongan_obat' => 'Antidiabetik',
                'jumlah_obat' => '60',
                'waktu_minum' => 'Pagi, Malam',
                'keterangan' => 'Obat untuk diabetes',
                'kontraindikasi' => 'Gagal ginjal',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Insulin',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '500 mg',
                'informasi_tambahan' => 'Hindari alkohol',
                'efek_samping' => 'Mulas',
                'indikasi' => 'Diabetes tipe 2',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 8,
                'nama_obat' => 'Lisinopril',
                'takaran_minum' => '10 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Pagi hari',
                'golongan_obat' => 'Antihipertensi',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi',
                'keterangan' => 'Obat untuk hipertensi',
                'kontraindikasi' => 'Hamil',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Diuretik',
                'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
                'kekuatan_sediaan' => '10 mg',
                'informasi_tambahan' => 'Periksa tekanan darah secara rutin',
                'efek_samping' => 'Pusing',
                'indikasi' => 'Hipertensi',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 8,
                'nama_obat' => 'Simvastatin',
                'takaran_minum' => '20 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Malam hari',
                'golongan_obat' => 'Hipolipidemik',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Malam',
                'keterangan' => 'Obat untuk kolesterol',
                'kontraindikasi' => 'Penyakit hati',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Antibiotik',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '20 mg',
                'informasi_tambahan' => 'Periksa kadar kolesterol secara rutin',
                'efek_samping' => 'Nyeri otot',
                'indikasi' => 'Hiperlipidemia',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 9,
                'nama_obat' => 'Amlodipine',
                'takaran_minum' => '5 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Pagi hari',
                'golongan_obat' => 'Antihipertensi',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi',
                'keterangan' => 'Obat untuk tekanan darah tinggi',
                'kontraindikasi' => 'Hamil',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Diuretik',
                'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
                'kekuatan_sediaan' => '5 mg',
                'informasi_tambahan' => 'Periksa tekanan darah secara rutin',
                'efek_samping' => 'Pusing',
                'indikasi' => 'Hipertensi',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 10,
                'nama_obat' => 'Omeprazole',
                'takaran_minum' => '20 mg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Kapsul',
                'aturan_pakai' => 'Sebelum makan',
                'golongan_obat' => 'Antasida',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi',
                'keterangan' => 'Obat untuk sakit maag',
                'kontraindikasi' => 'Alergi',
                'pola_makan' => 'Tidak ada',
                'interaksi_obat' => 'Warfarin',
                'petunjuk_penyimpanan' => 'Simpan di tempat kering',
                'kekuatan_sediaan' => '20 mg',
                'informasi_tambahan' => 'Minum dengan air',
                'efek_samping' => 'Sakit kepala',
                'indikasi' => 'Maag',
            ],
            [
                'id_apoteker' => 1,
                'id_pasien' => 10,
                'nama_obat' => 'Levothyroxine',
                'takaran_minum' => '50 mcg',
                'jml_kali_minum' => '1 kali',
                'bentuk_obat' => 'Tablet',
                'aturan_pakai' => 'Pagi hari',
                'golongan_obat' => 'Hormon',
                'jumlah_obat' => '30',
                'waktu_minum' => 'Pagi',
                'keterangan' => 'Obat untuk hipotiroidisme',
                'kontraindikasi' => 'Alergi',
                'pola_makan' => 'Sesuai anjuran dokter',
                'interaksi_obat' => 'Antikoagulan',
                'petunjuk_penyimpanan' => 'Simpan di suhu ruang',
                'kekuatan_sediaan' => '50 mcg',
                'informasi_tambahan' => 'Periksa kadar hormon tiroid secara rutin',
                'efek_samping' => 'Jantung berdebar',
                'indikasi' => 'Hipotiroidisme',
            ],
        ]);

        $obat->each(fn($put) => DB::table('obat')->insert($put));
    }
}
