<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PemeriksaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pemeriksaaan = collect([
            [
                'id_dokter' => 1,
                'id_pasien' => 1,
                'anamnesa' => 'Demam tinggi dan batuk',
                'diagnosis' => 'Harian',
                'golongan_darah' => 'A',
                'berat_badan' => 65,
                'tinggi_badan' => 170,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Sakit tenggorokan dan pilek',
                'suhu_tubuh' => 37.5,
                'nadi' => 88,
                'sistole' => 120,
                'diastole' => 80,
                'pernapasan' => 20,
                'medikamentosa' => 'Paracetamol, Amoxicillin',
                'non_medikamentosa' => 'Istirahat dan minum air putih',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 1,
                'id_pasien' => 2,
                'anamnesa' => 'Pusing dan mual',
                'diagnosis' => '2x sehari',
                'golongan_darah' => 'B',
                'berat_badan' => 70,
                'tinggi_badan' => 175,
                'merokok' => 'Ya',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Lemas dan tidak nafsu makan',
                'suhu_tubuh' => 36.8,
                'nadi' => 80,
                'sistole' => 110,
                'diastole' => 70,
                'pernapasan' => 18,
                'medikamentosa' => 'Antasida',
                'non_medikamentosa' => 'Makan teratur',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 1,
                'id_pasien' => 3,
                'anamnesa' => 'Batuk kronis',
                'diagnosis' => '3x sehari',
                'golongan_darah' => 'O',
                'berat_badan' => 55,
                'tinggi_badan' => 160,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Menyusui',
                'keluhan_awal' => 'Batuk kering sudah seminggu',
                'suhu_tubuh' => 37.0,
                'nadi' => 90,
                'sistole' => 130,
                'diastole' => 85,
                'pernapasan' => 22,

                'medikamentosa' => 'Obat batuk',
                'non_medikamentosa' => 'Minum hangat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 2,
                'id_pasien' => 4,
                'anamnesa' => 'Sakit kepala sebelah',
                'diagnosis' => 'Harian',
                'golongan_darah' => 'AB',
                'berat_badan' => 60,
                'tinggi_badan' => 165,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Migrain',
                'suhu_tubuh' => 36.5,
                'nadi' => 72,
                'sistole' => 115,
                'diastole' => 75,
                'pernapasan' => 16,
                'medikamentosa' => 'Ibuprofen',
                'non_medikamentosa' => 'Istirahat cukup',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 2,
                'id_pasien' => 5,
                'anamnesa' => 'Mual dan diare',
                'diagnosis' => 'Setiap gejala muncul',
                'golongan_darah' => 'O',
                'berat_badan' => 68,
                'tinggi_badan' => 172,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Hamil',
                'keluhan_awal' => 'Mual sejak pagi',
                'suhu_tubuh' => 37.2,
                'nadi' => 84,
                'sistole' => 125,
                'diastole' => 78,
                'pernapasan' => 19,

                'medikamentosa' => 'Oralit',
                'non_medikamentosa' => 'Istirahat, cairan cukup',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 3,
                'id_pasien' => 6,
                'anamnesa' => 'Demam ringan',
                'diagnosis' => '1x malam',
                'golongan_darah' => 'B',
                'berat_badan' => 50,
                'tinggi_badan' => 155,
                'merokok' => 'Ya',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Demam sejak semalam',
                'suhu_tubuh' => 38.0,
                'nadi' => 86,
                'sistole' => 118,
                'diastole' => 77,
                'pernapasan' => 20,

                'medikamentosa' => 'Paracetamol',
                'non_medikamentosa' => 'Kompres dingin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 3,
                'id_pasien' => 7,
                'anamnesa' => 'Pegal-pegal',
                'diagnosis' => '2x sehari',
                'golongan_darah' => 'A',
                'berat_badan' => 75,
                'tinggi_badan' => 180,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Pegal sejak kemarin',
                'suhu_tubuh' => 36.7,
                'nadi' => 78,
                'sistole' => 122,
                'diastole' => 82,
                'pernapasan' => 17,
                'medikamentosa' => 'Obat anti nyeri',
                'non_medikamentosa' => 'Peregangan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 4,
                'id_pasien' => 8,
                'anamnesa' => 'Lelah terus-menerus',
                'diagnosis' => 'Harian',
                'golongan_darah' => 'B',
                'berat_badan' => 64,
                'tinggi_badan' => 168,
                'merokok' => 'Ya',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Tidak bertenaga',
                'suhu_tubuh' => 36.6,
                'nadi' => 70,
                'sistole' => 110,
                'diastole' => 72,
                'pernapasan' => 18,
                'medikamentosa' => 'Vitamin B kompleks',
                'non_medikamentosa' => 'Tidur cukup',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 4,
                'id_pasien' => 9,
                'anamnesa' => 'Nyeri otot',
                'diagnosis' => 'Jika nyeri',
                'golongan_darah' => 'O',
                'berat_badan' => 58,
                'tinggi_badan' => 162,
                'merokok' => 'Tidak',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Nyeri setelah olahraga',
                'suhu_tubuh' => 36.9,
                'nadi' => 76,
                'sistole' => 115,
                'diastole' => 76,
                'pernapasan' => 18,
                'medikamentosa' => 'Obat nyeri otot',
                'non_medikamentosa' => 'Istirahat dan kompres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_dokter' => 5,
                'id_pasien' => 10,
                'anamnesa' => 'Pilek dan hidung tersumbat',
                'diagnosis' => '2x sehari',
                'golongan_darah' => 'A',
                'berat_badan' => 67,
                'tinggi_badan' => 173,
                'merokok' => 'Ya',
                'hamil_menyusui' => 'Tidak Keduanya',
                'keluhan_awal' => 'Tidak bisa mencium bau',
                'suhu_tubuh' => 36.3,
                'nadi' => 75,
                'sistole' => 117,
                'diastole' => 79,
                'pernapasan' => 17,

                'medikamentosa' => 'Dekongestan',
                'non_medikamentosa' => 'Uap hangat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $pemeriksaaan->each(fn($put) => DB::table('pemeriksaan_akhir')->insert($put));
    }
}
