<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PemeriksaaanAwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pemeriksaan = collect([
            [
                'id_pasien' => 1,
                'id_dokter' => 1,
                'tanggal_pemeriksaan' => '2024-01-10',
                'golongan_darah' => 'A',
                'berat_badan' => 70,
                'tinggi_badan' => 170,
                'suhu_tubuh' => 36.5,
                'nadi' => 80,
                'sistole' => 120,
                'diastole' => 80,
                'pernapasan' => 18,
                'merokok' => 'Tidak',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Pusing dan lemas',
                'ket_alergi_obat' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 2,
                'id_dokter' => 2,
                'tanggal_pemeriksaan' => '2024-01-12',
                'golongan_darah' => 'B',
                'berat_badan' => 60,
                'tinggi_badan' => 160,
                'suhu_tubuh' => 37.0,
                'nadi' => 85,
                'sistole' => 118,
                'diastole' => 79,
                'pernapasan' => 20,
                'merokok' => 'Tidak',
                'hamil/menyusui' => 'Hamil',
                'keluhan_awal' => 'Mual dan muntah',
                'ket_alergi_obat' => 'Paracetamol',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 3,
                'id_dokter' => 3,
                'tanggal_pemeriksaan' => '2024-01-15',
                'golongan_darah' => 'O',
                'berat_badan' => 75,
                'tinggi_badan' => 175,
                'suhu_tubuh' => 36.8,
                'nadi' => 78,
                'sistole' => 122,
                'diastole' => 81,
                'pernapasan' => 17,
                'merokok' => 'Ya',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Sesak napas',
                'ket_alergi_obat' => 'Sulfa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 4,
                'id_dokter' => 4,
                'tanggal_pemeriksaan' => '2024-01-18',
                'golongan_darah' => 'AB',
                'berat_badan' => 55,
                'tinggi_badan' => 155,
                'suhu_tubuh' => 36.9,
                'nadi' => 82,
                'sistole' => 115,
                'diastole' => 77,
                'pernapasan' => 19,
                'merokok' => 'Tidak',
                'hamil/menyusui' => 'Menyusui',
                'keluhan_awal' => 'Demam ringan',
                'ket_alergi_obat' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 5,
                'id_dokter' => 5,
                'tanggal_pemeriksaan' => '2024-01-20',
                'golongan_darah' => 'A',
                'berat_badan' => 80,
                'tinggi_badan' => 180,
                'suhu_tubuh' => 37.1,
                'nadi' => 76,
                'sistole' => 125,
                'diastole' => 85,
                'pernapasan' => 16,
                'merokok' => 'Ya',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Nyeri dada',
                'ket_alergi_obat' => 'Aspirin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 6,
                'id_dokter' => 6,
                'tanggal_pemeriksaan' => '2024-01-22',
                'golongan_darah' => 'O',
                'berat_badan' => 50,
                'tinggi_badan' => 150,
                'suhu_tubuh' => 36.4,
                'nadi' => 90,
                'sistole' => 110,
                'diastole' => 70,
                'pernapasan' => 21,
                'merokok' => 'Tidak',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Batuk',
                'ket_alergi_obat' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 7,
                'id_dokter' => 7,
                'tanggal_pemeriksaan' => '2024-01-24',
                'golongan_darah' => 'B',
                'berat_badan' => 85,
                'tinggi_badan' => 178,
                'suhu_tubuh' => 36.7,
                'nadi' => 88,
                'sistole' => 130,
                'diastole' => 90,
                'pernapasan' => 18,
                'merokok' => 'Ya',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Pegal-pegal',
                'ket_alergi_obat' => 'Amoxicillin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 8,
                'id_dokter' => 8,
                'tanggal_pemeriksaan' => '2024-01-26',
                'golongan_darah' => 'AB',
                'berat_badan' => 54,
                'tinggi_badan' => 162,
                'suhu_tubuh' => 36.3,
                'nadi' => 83,
                'sistole' => 116,
                'diastole' => 78,
                'pernapasan' => 20,
                'merokok' => 'Tidak',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Pusing ringan',
                'ket_alergi_obat' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 9,
                'id_dokter' => 9,
                'tanggal_pemeriksaan' => '2024-01-28',
                'golongan_darah' => 'A',
                'berat_badan' => 78,
                'tinggi_badan' => 172,
                'suhu_tubuh' => 36.6,
                'nadi' => 79,
                'sistole' => 124,
                'diastole' => 82,
                'pernapasan' => 19,
                'merokok' => 'Ya',
                'hamil/menyusui' => null,
                'keluhan_awal' => 'Sakit kepala',
                'ket_alergi_obat' => 'Ibuprofen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_pasien' => 10,
                'id_dokter' => 10,
                'tanggal_pemeriksaan' => '2024-01-30',
                'golongan_darah' => 'O',
                'berat_badan' => 62,
                'tinggi_badan' => 165,
                'suhu_tubuh' => 37.2,
                'nadi' => 84,
                'sistole' => 117,
                'diastole' => 76,
                'pernapasan' => 20,
                'merokok' => 'Tidak',
                'hamil/menyusui' => 'Hamil',
                'keluhan_awal' => 'Mual',
                'ket_alergi_obat' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $pemeriksaan->each(fn($data) => DB::table('pemeriksaan_awal')->insert($data));
    }
}
